cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/comp/xx_bitcoin_notes.html"  "/home/xah/web/xahlee_info/comp/xx_bitcoin_notes.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/comp/xx_ruby_notes.html"  "/home/xah/web/xahlee_info/comp/xx_ruby_notes.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/comp/xx_complexity_shell_in_emacs.html"  "/home/xah/web/xahlee_info/comp/xx_complexity_shell_in_emacs.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/comp/xx digital book vs paper book.txt"  "/home/xah/web/xahlee_info/comp/xx digital book vs paper book.txt"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/comp/xx_random_programing_bookmark.html"  "/home/xah/web/xahlee_info/comp/xx_random_programing_bookmark.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/MathGraphicsGallery_dir/Combinatorics_dir/xx-loopNPoints.html"  "/home/xah/web/xahlee_info/MathGraphicsGallery_dir/Combinatorics_dir/xx-loopNPoints.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/linux/xx_postgres_tutorial.html"  "/home/xah/web/xahlee_info/linux/xx_postgres_tutorial.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/tree/xx-tree.zip"  "/home/xah/web/xahlee_info/tree/xx-tree.zip"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/js/ex/xx-crash_os.html"  "/home/xah/web/xahlee_info/js/ex/xx-crash_os.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/js/ex/xx-crash_os.js"  "/home/xah/web/xahlee_info/js/ex/xx-crash_os.js"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/js/xx_css_properties.html"  "/home/xah/web/xahlee_info/js/xx_css_properties.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/js/xxnodejs_ref.html"  "/home/xah/web/xahlee_info/js/xxnodejs_ref.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/js/xxxx_schizoid.txt"  "/home/xah/web/xahlee_info/js/xxxx_schizoid.txt"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/xx-naomi_svg_29630/xx_JavaScript_date_79337.js"  "/home/xah/web/xahlee_info/xx-naomi_svg_29630/xx_JavaScript_date_79337.js"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/perl-python/xx-python_module_test.zip"  "/home/xah/web/xahlee_info/perl-python/xx-python_module_test.zip"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/perl-python/xx-python-sidebar-index-experiment.css"  "/home/xah/web/xahlee_info/perl-python/xx-python-sidebar-index-experiment.css"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/perl-python/xx03071.pyc"  "/home/xah/web/xahlee_info/perl-python/xx03071.pyc"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/perl-python/xx-python-sidebar-index-experiment.html"  "/home/xah/web/xahlee_info/perl-python/xx-python-sidebar-index-experiment.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/perl-python/xx-writing_a_server.html"  "/home/xah/web/xahlee_info/perl-python/xx-writing_a_server.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/kbd/xx_keyboard_layouts.js"  "/home/xah/web/xahlee_info/kbd/xx_keyboard_layouts.js"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/kbd/xx_keyboard_layouts.html"  "/home/xah/web/xahlee_info/kbd/xx_keyboard_layouts.html"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/mswin/xx_Windows_Control_Alt_Caps_lock_swap.zip"  "/home/xah/web/xahlee_info/mswin/xx_Windows_Control_Alt_Caps_lock_swap.zip"
cp "/home/xah/web/xahlee_org/diklo/yy_xahlee_info/xx-lbasic.css-2013-07-06-with-hover-xx.html"  "/home/xah/web/xahlee_info/xx-lbasic.css-2013-07-06-with-hover-xx.html"

