-*- coding: utf-8 -*-

2012-08-22

* The Misc Scripts of a Effete Hotshot

Xah's misc scripts. They are accumulated over the years. Some dates back to 1998.

Most are one-time-use-throw-away scripts, for managing my website. Most are trivial. Few are few hundred lines. Vast majority are text processing.

There are {perl, python, emacs lisp} scripts. Language used changed over the years.

* Coding Style

The coding style changes. Many coding style are experimental. For example, in perl, during a period i always used “use strict;”, but then abandoned it for a year just to see what happens. (nothing happens, actually. I don't really see it helps unless you are a perl beginner. Perl monger's wide-spread insistence on that is just clamor. If you really care, you better off not using perl. On one hand, the perl idiots say it's perl flexibility, yet they recommend always use “use strict;”. Paradoxical.)

Here's another example of style change. In perl, for a period i always use the 「q()」 form instead of 「''」 because the former has syntactical advantage, because it hold info of matching positions.

Another example: in elisp, many variables are greek chars. (See: 
〈Programing Style: Variable Naming: English Words Considered Harmful〉
http://xahlee.info/comp/programing_variable_naming.html
)

Also, most of the scripts are heavily functional style, regardless of language. There's no OOP here.

Also, they almost all sneer standard conventions. For example, lines runs more than 80 chars. See:
〈Programing: the Harm of Hard-wrapping Lines〉
http://xahlee.info/UnixResource_dir/writ/hard-wrap.html

* anti-hackers manifesto

See:
〈HTML5 Doctype, Validation, X-UA-Compatible, and Why Do I Hate Hackers〉
http://xahlee.info/js/html5_validation_doctype.html

〈Programing: Why Idiomatic Programing Are Bad〉
http://xahlee.info/comp/language_design_and_idioms.html

〈Why Software Suck: Design Patterns Quackery〉
http://xahlee.info/UnixResource_dir/writ/why_software_suck.html

〈Are You Intelligent Enough to Understand HTML5?〉
http://xahlee.info/UnixResource_dir/writ/html5_vs_intelligence.html

〈Paul Graham's Infatuation with the Concept of Hacker〉 http://xahlee.info/comp/Paul_Graham_language_design.html

〈What's the Difference Between Hacker and Tech Geeker?〉
http://xahlee.info/comp/tech_geeker_vs_hacker.html

〈What is a Tech Geeker?〉
http://xahlee.info/UnixResource_dir/writ/tech_geeker.html

See also:
〈Xah on Programing Languages〉
http://xahlee.info/comp/comp_lang.html

and finally, what's github for? Showing off, of course. If you have code that's actually valuable with a worth say 10% of your income, would you put it on github?
