(when (file-exists-p "/home/xah/web/xahlee_info/math/xx_math_blog.html") (print  ▮))

(let (ss)
  (setq ss "/home/xah/web/xahlee_info/math/xx_math_blog.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/cmaci/xx-howto_vs_whatis.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/validate_matching_brackets/xx/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_bitcoin_notes.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx-2013-05-21-put-gz-back-to-git.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_ruby_notes.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_unix_file_name.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_Douglas_Crockford_computing_history.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_complexity_shell_in_emacs.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_comp_blog.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx digital book vs paper book.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_keyboard.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx_random_programing_bookmark.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/comp/xx saga of bsof 2011-07-22.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/MathGraphicsGallery_dir/Combinatorics_dir/xx-loopNPoints.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/Netiquette_dir/xx why u write.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/linux/xx_postgres_tutorial.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/tree/xx-tree.zip") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/tree/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/tree/.htaccess") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/java-a-day/xx-java_lang_problems.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/java-a-day/xx-oop_reuse.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ocaml/xx_jargons_of_functional_programing.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ocaml/xx2.ml") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ocaml/xx_type.ml") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ocaml/xx_reading_file.ml") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ocaml/xx-map.ml") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ocaml/xx-system.ml") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/writ/xx-gen_math_exprs.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/writ/xx.py") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/writ/xx-logo-design-write.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/writ/xx-haskell_currying_jargon.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/writ/xx-rsync.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/writ/xx-currying_jargon.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-pike_says.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-hoarace.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-perlr.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-uhist.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx_paradigm.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-linx.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-xlingo.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx_perl_aticels.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx_unixfaq.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-rsync_bug.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/UnixResource_dir/xx/xx-perldoc_argument_reverse.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/EquiangularSpiral_dir/xx/xx-equiangular_spiral_scaling2.nb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/EquiangularSpiral_dir/xx/xx-equiangular_spiral_scaling.nb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/EquiangularSpiral_dir/xx/xx-equiangular_spiral_evolute.nb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/EquiangularSpiral_dir/xx-ggb-note.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Parabola_dir/xx-parabola_ggb_notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Tractrix_dir/xx-ggb_note.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Tractrix_dir/xx-ggb-notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Rose_dir/xx-ggb-notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/_curves_robert_yates/xx-gen_pages.el") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/_curves_robert_yates/xx-gen_links.el") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Clothoid_dir/xx-ggb-notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/CoordinateSystem_dir/xx-vectors.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/CoordinateSystem_dir/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx/xx-misc_curves.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx/xx-diff_geo.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx/xx-algebraic_curve.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx/xx-5point-conics.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ArchimedeanSpiral_dir/xx-ggb-notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Cardioid_dir/xx-cardioid_ggb_note.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Inversion_dir/xx-ggb-notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx-equiangular_spiral_caustic_ill.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx-hypotrochoids_template.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx-cardioid_gen.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx-template.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx conics_Pascal_theorem copy 2.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx conics tangent.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx-template.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx equiangular_spiral_ill.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx conics_Pascal_theorem2.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx-ellipse_all_props.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ggb/xx conics_Pascal_theorem copy 1.ggb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Sinusoid_dir/xx-trig_identities.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Sinusoid_dir/xx-herons_formula.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Intro_dir/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Circle_dir/xx-ggb-notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/Deltoid_dir/xx-ggb-notes.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx-img_index.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx-wiki.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx-2013-02-21-gsp-link-replace.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/3d/i/xxx.pov") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/3d/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/3d/xx-mma.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_web_study/multiply/xx.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_web_study/multiply/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_todo/xx-html-table.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_todo/xx-infinite-loop.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_todo/xx-js-game_square.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_todo/xx-swap_image_js.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_todo/xx-abu_prison.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx_todo/xx-trailing_mouse_pointer.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-tabs/xx2.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/ex/xx_js3d.js") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/ex/xx-crash_os.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/ex/xx_js3d.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/ex/xx-crash_os.js") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx4_css_menu.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_rotating_cube.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx4_css_menu.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-protovis.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx4_css_menu2.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-js_demo_tearable_cloth.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_webdev_blog.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_css_menu1.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_triangle.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_rotating_cube.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_css_properties.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xxnodejs_ref.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_menu_with_pure_css.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_pie_menu_2.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_pie_menu_2.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xxxx_schizoid.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_triangle.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_semi-circle_menu.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-js_demo_tearable_cloth.js") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-js_demo_tearable_cloth.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_web_dev_blog_write.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_plane_curve.js") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_plane_curve.htm") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_js_embed_tag_stat.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx_css_menu1.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/js/xx-css_semi-circle_menu.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/xx-naomi_svg_29630/xx_JavaScript_date_79337.js") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ruby/xx_rails_notes.rb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ruby/xx_ruby_notes.rb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/ruby/xx_syntax.rb") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/perl-python/xx-python_module_test.zip") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/perl-python/xx-python-sidebar-index-experiment.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/perl-python/xx03071.pyc") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/perl-python/xx-python-sidebar-index-experiment.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/perl-python/xx-writing_a_server.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/math_software/xx.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/webgl/xx.xml") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/webgl/xx1.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/webgl/xx.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/kbd/xx_keyboard_layouts.js") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/kbd/xx_keyboard_layouts.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/kbd/xx-css-figure-size-test.css") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/kbd/xx-css-figure-size-test.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/mswin/xx_PC_memory_.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/mswin/xx_QuicKeys.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/mswin/xx-fix-pc.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/mswin/xx-msconfig.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/mswin/xx_Windows_Control_Alt_Caps_lock_swap.zip") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/surface/xxx.el") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/haskell/xx/xx2.hs") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/haskell/xx-haskell_lang_notes.hs") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/script-samples/xx-search-help.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx/xx-com_object.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx/xx-output-unix-eol.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-function.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-hash.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-true-false.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-operators.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-variables.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-strings.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-array.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/syntax/xx-flow-control.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-launch-app-in-background.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-script-example.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-processes.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-syntax.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-todo.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-printing.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-regex.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-format_and_output.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-script.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx2.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-running-scripts.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx1.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-writing-file.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-methods.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-chinese-unicode.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx2.ps1") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/powershell/xx-find-param_alias.txt") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/visual_basic/xx2.vbs") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/php/xx-db.php") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/xx-lbasic.css-2013-07-06-with-hover-xx.html") (when (not (file-exists-p ss)) (print ss))
  (setq ss "/home/xah/web/xahlee_info/.htaccess") (when (not (file-exists-p ss)) (print ss)

))



• rm  /home/xah/web/xahlee_info/comp/validate_matching_brackets/xx
• rm  /home/xah/web/xahlee_info/UnixResource_dir/xx
• rm  /home/xah/web/xahlee_info/SpecialPlaneCurves_dir/EquiangularSpiral_dir/xx
• rm  /home/xah/web/xahlee_info/SpecialPlaneCurves_dir/ConicSections_dir/xx
• rm  /home/xah/web/xahlee_info/SpecialPlaneCurves_dir/xx
• rm  /home/xah/web/xahlee_info/js/xx
• rm  /home/xah/web/xahlee_info/haskell/xx
• rm  /home/xah/web/xahlee_info/powershell/xx
